services:
  mongoDB:
    image: mongo:latest
    container_name: mongoDB_summarizer
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - backend
    restart: always

networks:
  backend:

volumes:
  mongo_data: